"""Chat Service Module - Injects singleton WorkforceAgent."""

from app.agent.workforce_agent import WorkforceAgent, get_workforce_agent

class ChatService:
    """Service handling API requests by delegating to pre-compiled WorkforceAgent."""
    
    def __init__(self, agent: WorkforceAgent = None, services: dict = None):
        """Initializes ChatService with an existing WorkforceAgent instance.
        
        Args:
            agent (WorkforceAgent, optional): Pre-compiled WorkforceAgent instance. Defaults to singleton instance.
            services (dict, optional): Injected workforce services dict.
        """
        self.agent = agent or get_workforce_agent()
        self.services = services or {}

    async def generate_response(
        self,
        message: str,
        thread_id: str = "default_session",
        authenticated_employee_id: str = None,
        authenticated_employee_number: str = None
    ) -> str:
        """Asynchronously routes query to the pre-compiled workforce agent graph.
        
        Args:
            message (str): User query.
            thread_id (str, optional): Thread ID. Defaults to 'default_session'.
            authenticated_employee_id (str, optional): Authenticated employee ID.
            authenticated_employee_number (str, optional): Authenticated employee number.
            
        Returns:
            str: Generated assistant response.
        """
        # Pass the services and authentication details directly to the agent's run method
        result = await self.agent.run(
            question=message,
            thread_id=thread_id,
            services=self.services,
            authenticated_employee_id=authenticated_employee_id,
            authenticated_employee_number=authenticated_employee_number
        )
        return result.get("response", "No response generated by agent.")
