"""Add Phase 5 ML tables

Revision ID: e8d558423506
Revises: a56c3ce96284
Create Date: 2026-08-08 14:25:36.210689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d558423506'
down_revision: Union[str, None] = 'a56c3ce96284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_model_metadata_model_name'), 'model_metadata', ['model_name'], unique=True)
    op.create_table('skill_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('demand_category', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_predictions_id'), 'skill_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_skill_predictions_skill_id'), 'skill_predictions', ['skill_id'], unique=False)
    op.create_table('skill_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_risks_department_id'), 'skill_risks', ['department_id'], unique=False)
    op.create_index(op.f('ix_skill_risks_id'), 'skill_risks', ['id'], unique=False)
    op.create_table('workforce_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('current_headcount', sa.Integer(), nullable=False),
    sa.Column('projected_headcount', sa.Integer(), nullable=False),
    sa.Column('required_headcount', sa.Integer(), nullable=False),
    sa.Column('gap', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workforce_forecasts_department_id'), 'workforce_forecasts', ['department_id'], unique=False)
    op.create_index(op.f('ix_workforce_forecasts_id'), 'workforce_forecasts', ['id'], unique=False)
    op.create_table('employee_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('target_role_id', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['job_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_readiness_employee_id'), 'employee_readiness', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_readiness_id'), 'employee_readiness', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_readiness_id'), table_name='employee_readiness')
    op.drop_index(op.f('ix_employee_readiness_employee_id'), table_name='employee_readiness')
    op.drop_table('employee_readiness')
    op.drop_index(op.f('ix_workforce_forecasts_id'), table_name='workforce_forecasts')
    op.drop_index(op.f('ix_workforce_forecasts_department_id'), table_name='workforce_forecasts')
    op.drop_table('workforce_forecasts')
    op.drop_index(op.f('ix_skill_risks_id'), table_name='skill_risks')
    op.drop_index(op.f('ix_skill_risks_department_id'), table_name='skill_risks')
    op.drop_table('skill_risks')
    op.drop_index(op.f('ix_skill_predictions_skill_id'), table_name='skill_predictions')
    op.drop_index(op.f('ix_skill_predictions_id'), table_name='skill_predictions')
    op.drop_table('skill_predictions')
    op.drop_index(op.f('ix_model_metadata_model_name'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    # ### end Alembic commands ###
