"""Workforce Intelligence Agent Service Singleton Module."""

import time
import threading
from typing import Dict, Any, Optional
from app.agent.graph import get_workforce_app
from app.utils.logger import logger

class WorkforceAgent:
    """Singleton WorkforceAgent class wrapping the pre-compiled LangGraph StateGraph."""

    def __init__(self):
        """Initializes WorkforceAgent with pre-compiled graph."""
        self.app = get_workforce_app()

    async def run(
        self,
        question: str,
        thread_id: str = "default_session",
        services: dict = None,
        authenticated_employee_id: str = None,
        authenticated_employee_number: str = None
    ) -> Dict[str, Any]:
        """Asynchronously executes a user question through the pre-compiled LangGraph agent.
        
        Args:
            question (str): User input question.
            thread_id (str, optional): Conversation thread identifier for memory. Defaults to 'default_session'.
            services (dict, optional): Services injected via DI.
            authenticated_employee_id (str, optional): Authenticated employee ID.
            authenticated_employee_number (str, optional): Authenticated employee number.
            
        Returns:
            Dict[str, Any]: Execution result payload.
        """
        logger.info("Executing Graph")
        start_time = time.time()
        
        config = {
            "configurable": {
                "thread_id": thread_id,
                "services": services or {},
                "authenticated_employee_id": authenticated_employee_id,
                "authenticated_employee_number": authenticated_employee_number
            }
        }
        initial_state = {
            "question": question,
            "messages": [],
            "metadata": {
                "start_timestamp": start_time,
                "authenticated_employee_id": authenticated_employee_id,
                "authenticated_employee_number": authenticated_employee_number
            }
        }
        
        try:
            result = await self.app.ainvoke(initial_state, config=config)
            total_elapsed = time.time() - start_time
            
            final_response = result.get("final_response", "No response generated by agent.")
            intent = result.get("intent", "Unknown")
            tool_selected = result.get("tool_selected", "None")
            tool_result = result.get("tool_result", {})
            
            logger.info(f"Graph Completed (took {total_elapsed:.3f}s)")
            
            return {
                "response": final_response,
                "intent": intent,
                "tool_selected": tool_selected,
                "tool_result": tool_result,
                "execution_time_seconds": round(total_elapsed, 3)
            }
        except Exception as e:
            logger.error(f"Execution failure in WorkforceAgent: {e}")
            return {
                "response": f"An error occurred while executing workforce agent graph: {str(e)}",
                "intent": "Error",
                "tool_selected": "None",
                "tool_result": {"error": str(e)},
                "execution_time_seconds": round(time.time() - start_time, 3)
            }

_agent_instance: Optional[WorkforceAgent] = None
_agent_lock: threading.Lock = threading.Lock()

def get_workforce_agent() -> WorkforceAgent:
    """Returns the singleton WorkforceAgent instance.
    
    Returns:
        WorkforceAgent: Singleton WorkforceAgent holding compiled graph.
    """
    global _agent_instance
    if _agent_instance is None:
        with _agent_lock:
            if _agent_instance is None:
                _agent_instance = WorkforceAgent()
    return _agent_instance
